### PR TITLE
Spelling error in comment

### PR DESCRIPTION
**Pull request by drdla**

### CODE REVIEW

**Comment by csshugs** [comment]
Thanks for pointing this out!

However I need to reject this in the form being. This is not me being pedantic, but rather trying to comply to [our guidelines](https://github.com/inuitcss/inuitcss/blob/a243936606a3334be14bea7b3fbdc0db1b86f7cd/CONTRIBUTING.md#github-workflow).

Two things I'd like to note:
1. > Create a new branch entitled `tkt-<issue-number>`.

We already have a [long-running issue](https://github.com/inuitcss/inuitcss/issues/21)(#21) that we use to commit typos etc. to. So you should in this case use that issue to also name your feature branch respectively, e.g. `tkt-0024`.

2. > Start all commit messages with [refs #<issue-number>].

The [aforementioned issue](https://github.com/inuitcss/inuitcss/issues/21) given, your commit(s) should take the format defined in `CONTRIBUTING.md`, which is in this case: `[refs #21] Fix typo`. This has the advantage of GitHub automatically adding the commits to the timeline in the respective issue with that corresponding number (see #21).

@drdla 
I'd love if you could do this fix in a new branch with a compliant commit message. Again, I really don't like being pedantic, but I'm also keen in promoting our [contributing guidelines](https://github.com/inuitcss/inuitcss/blob/a243936606a3334be14bea7b3fbdc0db1b86f7cd/CONTRIBUTING.md#github-workflow).

**Comment by anselmh** [comment]
If you need help achieving this or want us to take over applying the changes, let us know here please so one of us can take over your commit, adapt and apply it manually according to our guidelines to our codebase. 

We value your contribution and the changes are completely valid but we need to keep watch of the project history very well to be able to maintain it easily and have proper ways to debug code later on, if necessary.

**Comment by herzinger** [comment]
Well, if you already merged the other one, just merge this one as well. Consistence is the only thing that matters for this kind of thing.

**Comment by csshugs** [comment]
Seems like, there are no strong opinions concerning this topic. Since I'm the one who requested the changes, I'll be the one merging this.

Thanks @drdla for fixing this!

**Pull request merged**
