### PR TITLE
Add ability to add !important to font-size mixin

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by florianbouvot** [comment]
LGTM.

**Comment by florianbouvot** [comment]
Not really important but in this "old" error message you use [`#{$variable-name}’](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.mixins.scss#L41) that not the case in newer error [important in font-size mixin](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.mixins.scss#L21) and [settings.global](https://github.com/inuitcss/inuitcss/blob/develop/settings/_settings.global.scss).

**Comment by csswizardry** [comment]
Do you mean the backticks/quotes are missing in the newer error messages?

**Comment by florianbouvot** [comment]
I just say that there is a difference but I don't know what the best.

**Pull request merged**
