### PR TITLE
[refs #331] @elseif statement not valid in all sass compiler versions

### LINKED ISSUE #331: @elseif causing problems in _tools.font-size.scss
Error: This at-rule is not allowed here.
  } @else {
    ^^^^^^
  css/tools/_tools.font-size.scss 20:5  root stylesheet

I installed sass globally using yarn . `yarn global add sass`, then ran `sass ./css/main.scss` and got the error mentioned above.

I'm on a Mac running Sierra with the following versions:

sass: 1.0.0-beta.2 compiled with dart2js 1.24.2
node: v8.7.0
npm: 5.5.1

### PR DESCRIPTION
**Pull request by GarethOates**
After a brand new download of inuitcss and copying the files over to a /css directory in my project.  I was unable to get the scss file to transpile without first modifying the two @elseif occurrences in the _tools.font-size.scss file.

Having checked the documentation at [sass_reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#if__) it would appear that @elseif is not valid.

This should resolve #331

### CODE REVIEW

**Comment by GarethOates** [comment]
This should resolve !331

**Comment by anselmh** [comment]
That said, @GarethOates would you mind altering your git commit message regardingly? I don’t think the current one reflects the truth and would love to have a correct git history to have useful context if we should need to debug the related code at some point again.

If you have no time or need help altering your commit message, please ping me again here. I can take over or tell you how to do this.

**Comment by GarethOates** [comment]
No worries, I'll take a look at this today and update accordingly.

**Comment by GarethOates** [comment]
Not sure why this Pull Request is not opening again.  My fork is 1 commit ahead of this.

**Comment by GarethOates** [comment]
I rebased and force pushed which I didn't realise was going to affect the Pull Request so much.  Learn something new every day I suppose.  Maybe there's something manual that can be done to fix the CI settings?  I've updated the wording in the commit.

**Comment by anselmh** [comment]
I actually don’t know what went wrong with CircleCI here. They say they can’t find the commit—yet it’s the correct commit hash that matches yours. I manually tested this now and merged it. Thanks for your rebase!

**Pull request merged**
