### PR TITLE
[refs #5] Split mixins and functions into separate files

### PR DESCRIPTION
**Pull request by csshugs**
As discussed in #5

### CODE REVIEW

**Comment by florianbouvot** [comment]
LGTM.

**Comment by csshugs** [comment]
Since this is a relatively huge change in code, I'd like to see a "LGTM" from everyone of @inuitcss/core before I merge this in.

**Comment by nenadjelovac** [comment]
LGTM.

**Comment by csswizardry** [comment]
I think we can also get rid of Halve, Hocus, and possibly Rem. They’re not used by anything yet. I will remove those files as granular commits in this branch and then we can revert them if we need to 👍

**Comment by csshugs** [comment]
@csswizardry Let's discuss Rem in #112

**Comment by csshugs** [comment]
...maybe it proofs itself useful for that.

**Comment by csshugs** [comment]
@anselmh Any concerns about this, before we merge this in?

**Comment by csswizardry** [comment]
Not here. LGTM.

**Comment by csshugs** [comment]
I'll wait for @anselmh. In this case I really want to have it approved 100%.

**Comment by anselmh** [comment]
All good!

**Pull request merged**
