### PR TITLE
[refs #38] Reorganize proprieties using HTML living Standard + alphabetical order

### PR DESCRIPTION
**Pull request by florianbouvot**

### CODE REVIEW

**Comment by florianbouvot** [comment]
@csshugs thoughts?

**Comment by anselmh** [comment]
Hm, I prefer the logical sorting as before. This said, I know it’s a highly subjective topic so ignore me if majority agrees.

**Comment by csshugs** [comment]
@florianbouvot I like it. But as I said, I don't have a strong opinion either.

So LGTM.

**Comment by csshugs** [comment]
@inuitcss/core 
I think we need some more feedback on this topic to be able to either merge this PR or decline it.

Thumbs please:

* 👍  = I don't care about this and have no opinion whatsoever so please **merge this PR** to get it out of my mind
* 👎  = Please leave everything as it is because of [reasons]

**Comment by csswizardry** [comment]
We’re very unlikely to ever edit this code—it gets installed and then left alone—so I’d be keen to close discussions on it as soon as possible. To that end, I’m gonna merge this in.

Cheers!

**Pull request merged**
