### PR TITLE
Simplify IE8 fallback

### PR DESCRIPTION
**Pull request by csshugs**
As discussed in #116

### CODE REVIEW

**Comment by nenadjelovac** [comment]
@csshugs sorry, I approved it by accident, and now I don't know how to unapprove it :) This comment still stands:

>@csshugs I think comments should be added so that everyone reading the code would understand why we have double font-size properties listed.

:)

**Comment by csshugs** [comment]
@nenadjelovac :)

Added notes about why we use duplicated `font-size` declaration. (And fixed Sass error. whooops.)

**Comment by csshugs** [comment]
Forgotten to update the tests 😞

**Comment by csshugs** [comment]
Alright. Tests are green.

@inuitcss/core Anymore concerns?

**Comment by nenadjelovac** [comment]
It looks good for me. But I think I'd wait for @csswizardry to see what he has to say on #116

**Comment by csshugs** [comment]
I'm now merging this, because I think this is safe to merge. All what this PR does, is taking a tiny bit of complexity out, i.e. instead of asking the user of either support IE8 or not, it just always supports IE8.

I guess until IE8 support can really be dropped (in 1-2 years maybe), this is a valid way to go. And the day we decide not to support IE8 anymore, we just drop the duplicated `px` declarations.

**Pull request merged**
