### PR TITLE
[refs #219] Install normalize.css as a dependency

### PR DESCRIPTION
**Pull request by florianbouvot**

### CODE REVIEW

**Comment by nenadjelovac** [comment]
@inuitcss/core I think we should update readme with short explanation what we're doing with normalize and why.

**Comment by anselmh** [comment]
> @inuitcss/core I think we should update readme with short explanation what we're doing with normalize (the postinstall thing) and why.

Yes, please. Would you mind to add this addition in the README to the Pull Request here?

**Comment by csshugs** [comment]
Did this ever worked locally? I always get:

```bash
> cp ./node_modules/normalize.css/normalize.css ./node_modules/inuitcss/generic/_generic.normalize.scss

cp: ./node_modules/normalize.css/normalize.css: No such file or directory
```

I think the problem is that, although it's a `postinstall` script, at the time it's being run, normalize.css is still not there, therefore can not be copied.

@inuitcss/core anyone get this working?

**Comment by csshugs** [comment]
When I run:

```bash
npm install --ignore-scripts
```

and then run manually:
```bash
cp ./node_modules/normalize.css/normalize.css /node_modules/inuitcss/generic/_generic.normalize.scss
```

it works.

**Comment by herzinger** [comment]
@csshugs if that is the only problem it's easy to solve. But let do some tests real quick.

**Comment by herzinger** [comment]
For me it worked just fine, with npm and 
```"postinstall": "cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss"```

Remember: we are coping it to inuitcss` own directory, which lives in the user `node_modules/`.

**Comment by csshugs** [comment]
> `"postinstall": "cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss`

No, doesn't work for me.

To make clear, what I try to do: I have a project folder in which is a `package.json`. In this `package.json` I have inuitcss as a dependency. When I run `npm install` in the project folder, I get:

```bash
cp: ./node_modules/normalize.css/normalize.css: No such file or directory
```

**Comment by csshugs** [comment]
node 6.9.1
npm 3.10.8

**Comment by csshugs** [comment]
What does work for me is this:

```bash
"postinstall": "cp ../normalize.css/normalize.css generic/_generic.normalize.scss",
```

**Comment by csshugs** [comment]
But changing directories with `../` feels wrong.

**Comment by csshugs** [comment]
@herzinger Do you have npm 2.x.x?

https://docs.npmjs.com/how-npm-works/npm3

**Comment by herzinger** [comment]
Oh, I see. I get the problem. It's because of the way npm distribute the dependencies directories. Facebook recently launched their own package manager just to get around this. I think I can solve it, just gimme a bit of time.

**Comment by herzinger** [comment]
@csshugs I'm running `node@3.10.8`, but that's not the problem. I don't have the correct setup ready here to test it the right way, the way you are doing it. Can you please try it with...
```json
"postinstall": "sleep 1 && cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss
```
...just to be sure? If it does not work, I'll do some node shenanigans.

**Comment by csshugs** [comment]
@herzinger 

> `"postinstall": "sleep 1 && cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss"

That doesn't work, either.

But [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) looks like a solution.

**To summarize my interpretation of what the problem seems to be:**

```bash
"postinstall": "cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss",
```

This `postinstall` script is being executed in the inuitcss package directory. That means it wants to copy a file in a node_modules subfolder inside of the inuitcss package folder. So the complete path looks something like this:

```
<project-folder>/node_modules/inuitcss/node_modules/normalize.css/normalize.css
```

**Comment by anselmh** [comment]
Shouldn‘t the solution just be as easy as `"postinstall": "cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss",`?

**Comment by csshugs** [comment]
@anselmh 

> houldn‘t the solution just be as easy as `"postinstall": "cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss",`?

That doesn't work on my machine (npm 3.10.8, see updated comment above)

**Comment by csshugs** [comment]
@anselmh Did you test it locally already and did it work? Which npm version do you have?

**Comment by anselmh** [comment]
@csshugs how do you test this, since we don’t have a published inuitcss version that has this? Because for me, on npm 3+ it works as well, tested locally either when having inuitcss as dependency or as a clone.

**Comment by herzinger** [comment]
@anselmh yes, that's what we started with
@csshugs that's exactly right. The problem is, npm is not reliable with the paths it creates when handling dependencies of dependencies. Sometimes, that path you just described is exactly what it does (that's why it's working for me).

**Comment by csshugs** [comment]
@anselmh 
Oh, sorry. I have a local inuitcss test project with a package.json which looks like this:

```json
{
  "name": "inuit-tester",
  "version": "0.0.1",
  "dependencies": {
    "inuitcss": "file:../inuitcss"
  }
}
```

and in `../inuitcss`, my inuitcss repository is located (with `tkt-0219 checked out)

**Comment by herzinger** [comment]
Just as a curiosity, [take a look at this](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/)

>The npm client installs dependencies into the node_modules directory non-deterministically. This means that based on the order dependencies are installed, the structure of a node_modules directory could be different from one person to another. These differences can cause “works on my machine” bugs that take a long time to hunt down.

**Comment by anselmh** [comment]
@herzinger This doesn’t apply though in our case as the postinstall script only runs after the dependencies are finished installing.

**Comment by anselmh** [comment]
@csshugs I fear that the `file: ../` is the issue here. Would you mind trying to properly test it locally by running `npm link` in your local inuitcss repo and then `npm link inuitcss` in your project?

**Comment by csshugs** [comment]
@herzinger 

> Sometimes, that path you just described is exactly what it does (that's why it's working for me).

As I understand it, [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) forces the dependency to be installed inside of inuitcss. I did it locally with a `npm-shrinkwrap.json` file:

```json
{
  "name": "inuitcss",
  "version": "6.0.0-beta.4",
  "dependencies": {
    "normalize.css": {
      "version": "5.0.0",
      "from": "normalize.css@>=5.0.0 <6.0.0",
      "resolved": "https://registry.npmjs.org/normalize.css/-/normalize.css-5.0.0.tgz"
    }
  }
}
```

This way, when running `npm install inuitcss` anywhere, the shrinkwrap.json makes sure to always install the normalize.css version that's defined in inuitcss' `package.json`, no matter if there are other dependencies referencing normalize.css with another version. And it makes it sure by installing this specific version inside of the inuitcss package, i.e. nested, i.e. like it was in npm version 1/2.

**Comment by anselmh** [comment]
I don’t think we should use shrinkwrap for inuitcss. It adds a lot of complexity, other new issues while pinning down the exact versions. Far from ideal for an open source project like this.

**Comment by herzinger** [comment]
>This doesn’t apply though in our case as the postinstall script only runs after the dependencies are finished installing.

@anselmh it does apply, as the problem is not the timing, but the path.

**Comment by csshugs** [comment]
I just rolled back my changes. I then run `npm install` in my project with this `package.json`:

```json
{
  "name": "inuit-tester",
  "version": "0.0.1",
  "dependencies": {
    "inuitcss": "https://github.com/inuitcss/inuitcss.git#tkt-0219"
  }
}
```

So I'm referencing this feature branch. 
And it still does not work. 

I get this error message

```bash
> cp ./node_modules/normalize.css/normalize.css ./generic/_generic.normalize.scss

cp: ./node_modules/normalize.css/normalize.css: No such file or directory
```

...before my terminal lists me all of the other installed dependencies.

Any ideas?

**Comment by anselmh** [comment]
1. Have you removed the node_modules folder before trying again?
2. If you did, can you share your `node_modules` and subtree’s content please?

**Comment by csshugs** [comment]
BTW: It works with `npm link`

**Comment by csshugs** [comment]
> Have you removed the node_modules folder before trying again?

Yes

> If you did, can you share your node_modules and subtree’s content please?

You mean to list all the packages in `node_modules`?

**Comment by herzinger** [comment]
>BTW: It works with `npm link`

why not use `npm link ... && ...` then?

**Comment by anselmh** [comment]
@csshugs I suspect some caching issues then if it works with `link` but not with a referenced branch repo.

**Comment by csshugs** [comment]
@herzinger 
Because inuitcss users don't use `npm link`. It has to work for them the same way, as I tried to do it. Or have I missed something?

**Comment by csshugs** [comment]
@anselmh 
> I suspect some caching issues then if it works with link but not with a referenced branch repo.

I already did `npm cache clean` and `npm cache clean -g`.

But I'm behind a proxy. Could that be a problem?

**Comment by herzinger** [comment]
@csshugs no, what I mean is to put the `npm link` in the postinstall hook, before the `cp`, with `&&`.

**Comment by anselmh** [comment]
Please don’t mix up things here. A user should never have to use `npm link`—we use this here to check out an in-development, local version of inuitcss instead of a published package.

@csshugs I’m not sure but I had this in the past, too, and it was mostly due to some weird stuff npm client is doing that isn’t cleared by `npm cache clean`.

**Comment by csshugs** [comment]
@anselmh I actually already uninstalled node/npm after first experiencing this issue in the morning and reinstalling it. I guess a computer restart could help 😄 .

I'' try that now (I have to eat something anyway). When this doesn't help it, I will try at home with my other MacBook.

I'll let you know when it works.

**Comment by herzinger** [comment]
I've been up working all night, so don't trust me too much right now hahaha

Is this problem only with npm? Does bower work fine?

**Comment by csshugs** [comment]
> Does bower work fine?

No, bower also doesn't work 😞 . bower don't even gives me an error, it just does not copy the file.

**Comment by herzinger** [comment]
Hum... I actually have an idea that should solve all our problems here, while also solving the issue about the reset partial name we raised in #206. The only problem that we would have to know it its being installed via bower or npm, which MAY make it inviable... I'll think a little more...

**Comment by herzinger** [comment]
Other option would be to use node to grab the package's path... Man, I need some sleep.

**Comment by anselmh** [comment]
> Other option would be to use node to grab the package's path... Man, I need some sleep.

There’s no need to rush here, so better grab some sleep :)

**Comment by herzinger** [comment]
wait, now after re-reading it all, it worked when @csshugs tested with `npm link` right? Them it was a problem of reference, caused by the `file/..`. It's working already hahaha

**Comment by csshugs** [comment]
@herzinger 
cc @inuitcss/core 
No, unfortunately. It worked with `npm link` and it also worked with `file:../`.

It didn't work with `npm install` and this `package.json`:
```json
{
  "name": "inuit-tester",
  "version": "0.0.1",
  "dependencies": {
    "inuitcss": "https://github.com/inuitcss/inuitcss.git#tkt-0219"
  }
}
```

But this is what has to work for the users later, right? Or does the final version first has to be published with `npm publish` to work the way I tried?

In other words: Please, can anyone who got this working on their machine give me a step-to-step instruction of how they've done it, so I can try it myself and see if I'm really that stupid or if we in fact have a problem here?

**Comment by herzinger** [comment]
@csshugs I don't even know if it is possible to link a branch as a dependency, but as I said in my PR, [this is the best way to test](http://podefr.tumblr.com/post/30488475488/locally-test-your-npm-modules-without-publishing).

BUT, as I said here, npm is inconsistent. The script I wrote deals with this inconsistency. With that it will work even if inuitcss is a dependency of a dependency of a dependency... and so on, of the user's project.

**Comment by csshugs** [comment]
@herzinger 
Unfortunately, your proposed solution didn't work either:

```
cp: ./node_modules/normalize.css/normalize.css: No such file or directory
```

@inuitcss/core 
@herzinger 
What *does* work for me is doing it with `npm link` and `bower link` locally. Does this suffices to be sure it also works when this PR is merged and published? If that's the case, I would give this a go.

**Comment by csshugs** [comment]
By going through this thread, it kinda gets obvious how fragile it can be to rely on an extra script to handle such things. It's a script that runs on the users machine. We just cannot control what happens there. If one thing goes wrong, it would be at least annoying for the user. 

If we continue delivering normalize within the framework, it's always bulletproof for the inuitcss user.

Please, let's not prioritize our developer convenience over the users convenience!

**Comment by herzinger** [comment]
My script would work in any environment, so that's not the point, and it's not the reason it got rejected. I'll give it some more though and get back at you when I think of a agreeable solution.

**Pull request closed without merging**
