### PR TITLE
Add basic tags styles

### PR DESCRIPTION
**Pull request by daliyajohn**

### CODE REVIEW

**Comment by Jamiewarb** [comment]
Not sure if there's any discussion around these tag styles yet, but I wonder a few things about this.

Firstly, standards wise, should the file be called `_elements.tags.scss` instead of `_tags.scss`?

Then also the circleci test fails on your `0px`, which should just be `0`.

Then lastly I wonder if this is more opinionated than Inuit is going for? We have h1-h6 with sizings, but they at least have the argument of semantics to back them up.

I wonder if this is a little far, especially defining a default size for `span`? At the very least, I imagine the `p` var should initialise to the base font size, not an arbitrary number. And removing margins from all p tags is quite a large step too.

I wonder what others views are

**Comment by yourownmood** [comment]
Could you please have a look at [CONTRIBUTING.md](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md) for the contributing guidelines.

- Create an issue
- Create a branch with the issue number referenced
- Include this issue number in all your commits
- Change the branch you are merging towards to develop
- Include your changes in de CHANGELOG.md

**Comment by daliyajohn** [comment]
Hai,
      Your suggestions was really good. I did that corrections also send
pull request. Please check when you get time.

Thanks and Regards
Daliya John

**Comment by herzinger** [comment]
Besides not following the guidelines, this makes absolutely no sense at all, sorry. What's the point of this pull request? 

`p` naturally inherits the document's text styles, and as @Jamiewarb said, we do not want to remove margins. Why would all `span` elements, generic inline-level elements that sit on text blocks, have a predefined size? And what is `text`? This adds nothing, solves less and is plain wrong.

**Comment by csshugs** [comment]
First of all, thanks @daliyajohn for the effort of proposing a PR for something you considered useful for the framework. 

However, there are a few formal things (already mentioned by @Jamiewarb and @yourownmood) that prevent this PR from being merged. Please head over to our [`CONTRIBUTING.md`](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md) file to find information about how we imagine contribution to happen by other contributors.

For such proposals like yours, it would be more pragmatic in general to open an issue and first discuss, if the feature you have in mind makes sense for the project. This way, if an idea is considered not worth being integrated into the framework, there is no need for the effort of writing code and opening a PR.

Concerning this specific proposal, I'm afraid this is far too opinionated for being incorporated into the framework. Assigning another arbitrary font-size as `$inuit-global-font-size` for the `<p>` element does not really makes sense, since the `<p>` element already inherits the global-font-size from the `<html>` element, defined in [`_elements.page.scss`](https://github.com/inuitcss/inuitcss/blob/7284ae4802a48ed6546041f9f4df32cbda16b03b/elements/_elements.page.scss#L18). Adding a specific font-size for a `<span>` globally is also far too opinionated. I'm also not sure, what the `<text>` element is and if we need to define a font-size for that.

Thanks again for proposing this PR, but for the reasons mentioned above, we will not merge this feature in. Thanks for the effort, though. Feel free to open an issue if you have any further ideas of how to improve the framework.

**Comment by LayZeeDK** [comment]
The `<text>` element is used in SVGs.

**Pull request closed without merging**
