### PR TITLE
Added additional flush modifiers to box object.

### PR DESCRIPTION
**Pull request by erfanimani**

### CODE REVIEW

**Comment by zomars** [comment]
I've actually use my own version of this in many projects. My naming is a little bit different tho: `o-box--flush-vertical`and `o-box--flush-horizontal`.

**Comment by erfanimani** [comment]
@zomars, nice. I actually got the naming from the flush utility classes in the previous inuitcss library: http://terabytenz.github.io/inuit.css-kitchensink/

**Comment by zomars** [comment]
Oh yeah, I remember the kitchensink!

**Comment by herzinger** [comment]
Is that something used frequently enough to require object modifiers? You can achieve the exact same with the spacing utilities, and I usually go as far as extending that suit with vertical and horizontal versions using the constructor maps in most projects.

**Comment by erfanimani** [comment]
Thanks for the message @herzinger. You might be right - let me have a look and see if we're not duplicating anything. From what I remember, the spacing utilities have `!important`, so they're can't be used in a lot of scenarios. Will check out constructor maps.

**Comment by herzinger** [comment]
Yes, they do have `!important` like any utility. Since they are pretty explicitly single resposability classes, every occasion they are used they SHOULD be enforced. The only situation it might cause problem is in responsive code, but since the last release the framework ships with responsive spacing, so this is solved.

On that note, I might start a separate issue asking for the responsive map to mirror the default regular map, since it seams more natural and would require less setup for stuff like that, and maybe even get vertical and horizontal variants out of the box. That being said, all the tools to achieve what is discussed here already exists, and this is the best way in my opinion.

**Comment by herzinger** [comment]
On another note, please check out our [contributing guidelines](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md). We have a proper workflow for pull requests that involves opening an issue for discussion and referencing it, and also naming conventions for branches and stuff like that. 

We should wait for input from the core members, but in my opinion this addition is not needed, but the conversation is valid. This kind of topic shows up a lot, in my view, because of our current lack of documentation outside of in-code commenting and usage examples. 

For that reason, I also manage an [unofficial slack channel](https://herzinger.typeform.com/to/h6e3Km) were the most common questions are about the _proper_, _better_ or even _multiple_ ways to achieve simple common stuff like this. Fell free to join and ask away, and to keep contributing from now on.

**Comment by erfanimani** [comment]
Thanks for taking the time and writing this up @herzinger - for some reason I wasn't aware of the responsive spacing utility (and I usually use code as documentation!). Agreed with mirroring regular spacing map in the responsive version. Can be closed.

**Pull request closed without merging**
