### PR TITLE
fix build badge

### PR DESCRIPTION
**Pull request by tymondesigns**
Adding the branch to the circleci badge so that it doesn't show a failing status based on unmerged PR's

### CODE REVIEW

**Comment by csshugs** [comment]
@tymondesigns 
IMO, it should point to the master branch instead of the develop branch, doesn't it?
Everyone is interested to see if the **master** branch is green, or am I wrong?

**Comment by herzinger** [comment]
@csshugs you are right

**Comment by anselmh** [comment]
This has been manually amended by me, merged manually while maintaining attribution. It‘s now in develop as per 3a0fb089233cce6fd628dc21a4435bb1a64a7d3c.

**Comment by herzinger** [comment]
@anselmh but should that have been done at all?

**Pull request closed without merging**
