### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by nicoqh**

### CODE REVIEW

**Comment by csshugs** [comment]
Thanks for pointing this out!

However I need to reject this in the form being. This is not me being pedantic, but rather trying to comply to [our guidelines](https://github.com/inuitcss/inuitcss/blob/a243936606a3334be14bea7b3fbdc0db1b86f7cd/CONTRIBUTING.md#github-workflow).

Two things I'd like to note:
1. > Create a new branch entitled `tkt-<issue-number>`.

We already have a [long-running issue](https://github.com/inuitcss/inuitcss/issues/21)(#21) that we use to commit typos etc. to. So you should in this case use that issue to also name your feature branch respectively, e.g. `tkt-0024`.

2. > Start all commit messages with [refs #<issue-number>].

The [aforementioned issue](https://github.com/inuitcss/inuitcss/issues/21) given, your commit(s) should take the format defined in `CONTRIBUTING.md`, which is in this case: `[refs #21] Fix typo`. This has the advantage of GitHub automatically adding the commits to the timeline in the respective issue with that corresponding number (see #21).

@nicoqh 
I'd love if you could do this fix in a new branch with a compliant commit message. Again, I really don't like being pedantic, but I'm also keen in promoting our [contributing guidelines](https://github.com/inuitcss/inuitcss/blob/a243936606a3334be14bea7b3fbdc0db1b86f7cd/CONTRIBUTING.md#github-workflow).

**Comment by nicoqh** [comment]
No problem, @csshugs ! I wasn't sure a new issue was warranted for a typo, and I took inspiration from an old commit (probably too old). And I didn't see the general tidy-up issue. Sorry about that. I'll fix it.

**Comment by csshugs** [comment]
@nicoqh No problem, don't sweat it!

> Clone the repo, commit my fixes to the existing branch "tkt-0021", request to merge "me/inuitcss:tkt-0021" into "inuitcss/inuitcss:develop"? Or into "inuitcss/inuitcss:tkt-0021"?

Into "inuitcss/inuitcss:develop".

**Comment by nicoqh** [comment]
> Into "inuitcss/inuitcss:develop".

Such a PR (inuitcss/inuitcss:tkt-0021 <-- me/inuitcss:tkt-0021) would include [5 other commits](https://github.com/inuitcss/inuitcss/compare/develop...inuitcss:tkt-0021?expand=1) from tkt-0021 that haven't been merged yet. Are you sure I'm not supposed to send the PR (one commit) to tkt-0021, so that you (the team) can merge the branch into develop at your own discretion? Or do you want the whole branch merged into develop now?

**Comment by csshugs** [comment]
>  Or do you want the whole branch merged into develop now as a result of my PR?

Yeah, this would be a good opportunity to move that stuff back into develop, so go ahead.

**Pull request closed without merging**
