### PR TITLE
[generic.reset] Add reset styles for fieldset

### PR DESCRIPTION
**Pull request by csshugs**
As discussed in #156 

```scss
min-width: min-content;
```

is likely not what you want, and the browser-default `border` declaration seems a bit too opinionated.

### CODE REVIEW

**Comment by florianbouvot** [comment]
@csshugs I have no opinion about it 😕

**Comment by csshugs** [comment]
I'm not sure, too.

@inuitcss/core What about the others?

**Comment by herzinger** [comment]
Removing the border is what is optioned in my opinion, but I am okay with that much, myself. 

Just keep in mind: 
1. It would force users who want bordered fieldsets to add css to remove other piece of css, but I guess it's somewhat common on resets.
2. Is the default border inconsistent across platforms? I ask because removing this kind of inconsistencies is the primary goal of a css reset. Sensible defaults are usually normalize's thing.

**Comment by anselmh** [comment]
For reset.css this would be perfectly fine, since it resets the style completely. Therefore I’m up for adding this.
As @herzinger said, if you want a border here, you’d need to add CSS again but this is what a reset.css is about. If you’re uncomfortable with this, use normalize instead.

But since I’m not using reset.css at all anywhere, my opinion here might not count too much. ;)

**Comment by nenadjelovac** [comment]
LGTM.

**Pull request merged**
