### PR TITLE
Move from global settings to core settings

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by florianbouvot** [comment]
LGTM.

**Comment by nenadjelovac** [comment]
@csswizardry should variables in example files be prefixed with `$inuit-`?

**Comment by csshugs** [comment]
@nenadjelovac 
> @csswizardry should variables in example files be prefixed with $inuit-?

Good question! Because it's an example file which, when copied and pasted by the user, is not a part of the inuitcss framework annymore, I would not prefix this. At least I wouldn't do this as an inuitcss user.
But then it has to be changed [here](https://github.com/inuitcss/inuitcss/blob/develop/settings/_example.settings.config.scss#L8) and [here](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_example.utilities.widths.scss#L15) as well.

**Comment by csswizardry** [comment]
@nenadjelovac: Good spot, thank you!

@csshugs: Those need to stay prefixed because they are actually used by inuitcss.

**Comment by csswizardry** [comment]
@inuitcss/core: Good for merge with 24f3568?

**Comment by nenadjelovac** [comment]
@csswizardry I'd say so.

**Comment by csshugs** [comment]
> Those need to stay prefixed because they are actually used by inuitcss.

Yeah right, overlooked that.

**Pull request merged**
