### PR TITLE
[refs #139] add ignore to bower.json

### PR DESCRIPTION
**Pull request by tymondesigns**
see #139 

did I miss anything?

### CODE REVIEW

**Comment by tymondesigns** [comment]
in-fact I guess `node_modules` & `bower_components` are not necessary eh?

**Comment by anselmh** [comment]
> in-fact I guess `node_modules` & `bower_components` are not necessary eh?

They are afaik, since they’re likely there when publishing a new version. At least, this is the case for npm, but I think bower creates the version from git remotes, not from the source?

**Comment by anselmh** [comment]
What about `.npmignore`?

**Comment by tymondesigns** [comment]
> but I think bower creates the version from git remotes, not from the source?

Yea bower pulls from git remote so they will never exist anyway

> What about .npmignore?

That's already covered by `"**/.*"`

**Comment by tymondesigns** [comment]
👍

**Pull request merged**
